module.exports = {
    TODO_CREATE: 'TODO_CREATE',
    TODO_COMPLETED: 'TODO_COMPLETED',
    TODO_UNCOMPLETED: 'TODO_UNCOMPLETED',
    TODO_DELETE: 'TODO_DELETE',
    TODO_CHANGE_POSITION: 'TODO_CHANGE_POSITION',
    TODO_CHANGE_COLLECTION: 'TODO_CHANGE_COLLECTION'
};
