module.exports = {
    TODO_CREATE: 'TODO_CREATE',
    TODO_EDIT: 'TODO_EDIT',
    TODO_COMPLETED: 'TODO_COMPLETED',
    TODO_UNCOMPLETED: 'TODO_UNCOMPLETED',
    TODO_DELETE: 'TODO_DELETE',
    TODO_CHANGE_POSITION: 'TODO_CHANGE_POSITION',
    TODO_CHANGE_COLLECTION: 'TODO_CHANGE_COLLECTION',
    TODO_ENTER_EDIT_MODE: 'TODO_ENTER_EDIT_MODE',
    TODO_DELETE_CURRENTLY_SELECTED: 'TODO_DELETE_CURRENTLY_SELECTED',
    TODO_INDENT: 'TODO_INDENT',
    TODO_UNINDENT: 'TODO_UNINDENT'
};
